# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a4bd556df0ffc570aa2aba9d074df029a3658e9f06eec0794abcf8f09c704944f942b6fd7f690d742840cec222747f4253e11a8e7660e7337e2f8d979aeb9d7

test:
  secret_key_base: 03ef1f63c98501a4c05e84aa2cd210cf99f81852a43bb4ac4ef304d3c6ce173f71ea91ee7459e9c5f99937623c5ca45ee51ceecac95862de910b4abbbeddf94f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
